name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1